name: betaVAEDemo
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - cpuonly
  - ipywidgets
  - ipython
  - ipython_genutils
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - voila
  - matplotlib-base
  - matplotlib-inline
  - numpy
  - natsort
  - pickleshare
  - imageio
  - ipympl
  - scipy
  - pytorch
  - pytorch-lightning
  - h5py
  - torchvision
