name: betaVAEDemo
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - ipython=8.4.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jupyter_client=7.4.1=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=5.2.0=py310hff52083_0
  - jupyter_server=1.23.5=pyhd8ed1ab_0
  - jupyterlab=3.4.4=py310h06a4308_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.19.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - voila=0.4.0=pyhd8ed1ab_0
  - matplotlib-base=3.6.2=py310h8d5ebf3_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - numpy=1.22.3=py310h4f1e569_0
  - numpy-base=1.22.3=py310hf2716ce_0
  - natsort=7.1.1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - imageio=2.25.0=pyh24c5eb1_0
  - ipympl=0.9.2=pyhd8ed1ab_0
  - scipy=1.7.3=py310h4f1e569_0
  - pytorch=1.13
  - pytorch-lightning=1.8.1=pyhd8ed1ab_0
  - h5py==3.7.0
  - torchvision=0.14.1
