name: betaVAEDemo
channels:
- pytorch
- conda-forge
- nodefaults
dependencies:
- imageio==2.36.0
- ipython==8.29.0
- ipympl==0.9.4
- voila==0.5.8
- ipywidgets==8.1.5
- matplotlib-base==3.9.2
- numpy==2.1.2
- pytorch==2.5.0
- scipy==1.14.1
