name: betaVAEDemo
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - ipython=8.29.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - voila=0.5.8=pyhd8ed1ab_1
  - matplotlib-base=3.9.2=py312hd3ec401_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - numpy=2.1.2=py312h58c1407_0
  - natsort=7.1.1
  - pickleshare=0.7.5=py_1003
  - imageio=2.36.0=pyh12aca89_1
  - ipympl=0.9.4=pyhd8ed1ab_0
  - scipy=1.14.1=py312h62794b6_1
  - pytorch=2.5.0=py3.12_cpu_0
  - pytorch-lightning=2.4.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py312hedeef09_102
  - torchvision